apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: demo-dev
spec:
  hard:
    requests.cpu: '1'
    requests.memory: 1Gi
    limits.cpu: '2'
    limits.memory: 2Gi
  scopes:
  - NotTerminating 
