apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: demo-dev
spec:
  limits:
    - type: "Container"
      max:
        cpu: "2" 
        memory: "1Gi" 
      min:
        cpu: "100m" 
        memory: "256Mi" 
      default:
        cpu: "200m" 
        memory: "256Gi" 
      defaultRequest:
        cpu: "200m" 
        memory: "256Mi" 
