apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    app: petclinic
    app.kubernetes.io/component: petclinic
    app.kubernetes.io/instance: petclinic
    app.kubernetes.io/part-of: petclinic
  name: petclinic
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/pittar/petclinic:dev
    from:
      kind: DockerImage
      name: quay.io/pittar/petclinic:dev
    importPolicy: {}
    name: dev
    referencePolicy:
      type: Source
